/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Theme } from "./utils/themes";
import { Update } from "./types";
export { Theme } from "./utils/themes";
export { Update } from "./types";
export namespace Components {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        /**
          * @default 'count'
         */
        "indicator": 'count' | 'dot';
        "light"?: Theme;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        "scope"?: string;
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
        "toggle": () => Promise<void>;
    }
    interface ChangebotPanel {
        "close": () => Promise<void>;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode": 'modal' | 'drawer-left' | 'drawer-right';
        "open": () => Promise<void>;
        "scope"?: string;
        "setUpdates": (updates: Update[]) => Promise<void>;
        "theme"?: Theme;
        /**
          * CSS selector for elements that should open the panel when clicked. Uses event delegation on the document, so elements added after mount also work. Example: `trigger=".open-updates"`.
         */
        "trigger"?: string;
    }
    interface ChangebotProvider {
        "baseUrl"?: string;
        "mockData"?: string;
        "preview"?: boolean;
        /**
          * @default 'default'
         */
        "scope": string;
        "slug"?: string;
        "userData"?: string;
        "userId"?: string;
    }
    interface ChangebotToast {
        /**
          * @default false
         */
        "confetti": boolean;
        /**
          * @default 351
         */
        "confettiParticleCount": number;
        /**
          * @default 0.8
         */
        "confettiScalar": number;
        /**
          * @default 130
         */
        "confettiSpread": number;
        /**
          * @default 46
         */
        "confettiStartVelocity": number;
        "dark"?: Theme;
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
        "scope"?: string;
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
    }
}
declare global {
    interface HTMLChangebotBadgeElement extends Components.ChangebotBadge, HTMLStencilElement {
    }
    var HTMLChangebotBadgeElement: {
        prototype: HTMLChangebotBadgeElement;
        new (): HTMLChangebotBadgeElement;
    };
    interface HTMLChangebotBannerElement extends Components.ChangebotBanner, HTMLStencilElement {
    }
    var HTMLChangebotBannerElement: {
        prototype: HTMLChangebotBannerElement;
        new (): HTMLChangebotBannerElement;
    };
    interface HTMLChangebotPanelElement extends Components.ChangebotPanel, HTMLStencilElement {
    }
    var HTMLChangebotPanelElement: {
        prototype: HTMLChangebotPanelElement;
        new (): HTMLChangebotPanelElement;
    };
    interface HTMLChangebotProviderElement extends Components.ChangebotProvider, HTMLStencilElement {
    }
    var HTMLChangebotProviderElement: {
        prototype: HTMLChangebotProviderElement;
        new (): HTMLChangebotProviderElement;
    };
    interface HTMLChangebotToastElement extends Components.ChangebotToast, HTMLStencilElement {
    }
    var HTMLChangebotToastElement: {
        prototype: HTMLChangebotToastElement;
        new (): HTMLChangebotToastElement;
    };
    interface HTMLElementTagNameMap {
        "changebot-badge": HTMLChangebotBadgeElement;
        "changebot-banner": HTMLChangebotBannerElement;
        "changebot-panel": HTMLChangebotPanelElement;
        "changebot-provider": HTMLChangebotProviderElement;
        "changebot-toast": HTMLChangebotToastElement;
    }
}
declare namespace LocalJSX {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        /**
          * @default 'count'
         */
        "indicator"?: 'count' | 'dot';
        "light"?: Theme;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotPanel {
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode"?: 'modal' | 'drawer-left' | 'drawer-right';
        "scope"?: string;
        "theme"?: Theme;
        /**
          * CSS selector for elements that should open the panel when clicked. Uses event delegation on the document, so elements added after mount also work. Example: `trigger=".open-updates"`.
         */
        "trigger"?: string;
    }
    interface ChangebotProvider {
        "baseUrl"?: string;
        "mockData"?: string;
        "preview"?: boolean;
        /**
          * @default 'default'
         */
        "scope"?: string;
        "slug"?: string;
        "userData"?: string;
        "userId"?: string;
    }
    interface ChangebotToast {
        /**
          * @default false
         */
        "confetti"?: boolean;
        /**
          * @default 351
         */
        "confettiParticleCount"?: number;
        /**
          * @default 0.8
         */
        "confettiScalar"?: number;
        /**
          * @default 130
         */
        "confettiSpread"?: number;
        /**
          * @default 46
         */
        "confettiStartVelocity"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position"?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
        "scope"?: string;
        "theme"?: Theme;
    }

    interface ChangebotBadgeAttributes {
        "theme": Theme;
        "scope": string;
        "light": Theme;
        "dark": Theme;
        "indicator": 'count' | 'dot';
        "count": number;
    }
    interface ChangebotBannerAttributes {
        "theme": Theme;
        "scope": string;
        "light": Theme;
        "dark": Theme;
    }
    interface ChangebotPanelAttributes {
        "theme": Theme;
        "scope": string;
        "light": Theme;
        "dark": Theme;
        "mode": 'modal' | 'drawer-left' | 'drawer-right';
        "trigger": string;
    }
    interface ChangebotProviderAttributes {
        "slug": string;
        "userId": string;
        "userData": string;
        "scope": string;
        "baseUrl": string;
        "mockData": string;
        "preview": boolean;
    }
    interface ChangebotToastAttributes {
        "theme": Theme;
        "scope": string;
        "light": Theme;
        "dark": Theme;
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
        "confetti": boolean;
        "confettiParticleCount": number;
        "confettiSpread": number;
        "confettiStartVelocity": number;
        "confettiScalar": number;
    }

    interface IntrinsicElements {
        "changebot-badge": Omit<ChangebotBadge, keyof ChangebotBadgeAttributes> & { [K in keyof ChangebotBadge & keyof ChangebotBadgeAttributes]?: ChangebotBadge[K] } & { [K in keyof ChangebotBadge & keyof ChangebotBadgeAttributes as `attr:${K}`]?: ChangebotBadgeAttributes[K] } & { [K in keyof ChangebotBadge & keyof ChangebotBadgeAttributes as `prop:${K}`]?: ChangebotBadge[K] };
        "changebot-banner": Omit<ChangebotBanner, keyof ChangebotBannerAttributes> & { [K in keyof ChangebotBanner & keyof ChangebotBannerAttributes]?: ChangebotBanner[K] } & { [K in keyof ChangebotBanner & keyof ChangebotBannerAttributes as `attr:${K}`]?: ChangebotBannerAttributes[K] } & { [K in keyof ChangebotBanner & keyof ChangebotBannerAttributes as `prop:${K}`]?: ChangebotBanner[K] };
        "changebot-panel": Omit<ChangebotPanel, keyof ChangebotPanelAttributes> & { [K in keyof ChangebotPanel & keyof ChangebotPanelAttributes]?: ChangebotPanel[K] } & { [K in keyof ChangebotPanel & keyof ChangebotPanelAttributes as `attr:${K}`]?: ChangebotPanelAttributes[K] } & { [K in keyof ChangebotPanel & keyof ChangebotPanelAttributes as `prop:${K}`]?: ChangebotPanel[K] };
        "changebot-provider": Omit<ChangebotProvider, keyof ChangebotProviderAttributes> & { [K in keyof ChangebotProvider & keyof ChangebotProviderAttributes]?: ChangebotProvider[K] } & { [K in keyof ChangebotProvider & keyof ChangebotProviderAttributes as `attr:${K}`]?: ChangebotProviderAttributes[K] } & { [K in keyof ChangebotProvider & keyof ChangebotProviderAttributes as `prop:${K}`]?: ChangebotProvider[K] };
        "changebot-toast": Omit<ChangebotToast, keyof ChangebotToastAttributes> & { [K in keyof ChangebotToast & keyof ChangebotToastAttributes]?: ChangebotToast[K] } & { [K in keyof ChangebotToast & keyof ChangebotToastAttributes as `attr:${K}`]?: ChangebotToastAttributes[K] } & { [K in keyof ChangebotToast & keyof ChangebotToastAttributes as `prop:${K}`]?: ChangebotToast[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "changebot-badge": LocalJSX.IntrinsicElements["changebot-badge"] & JSXBase.HTMLAttributes<HTMLChangebotBadgeElement>;
            "changebot-banner": LocalJSX.IntrinsicElements["changebot-banner"] & JSXBase.HTMLAttributes<HTMLChangebotBannerElement>;
            "changebot-panel": LocalJSX.IntrinsicElements["changebot-panel"] & JSXBase.HTMLAttributes<HTMLChangebotPanelElement>;
            "changebot-provider": LocalJSX.IntrinsicElements["changebot-provider"] & JSXBase.HTMLAttributes<HTMLChangebotProviderElement>;
            "changebot-toast": LocalJSX.IntrinsicElements["changebot-toast"] & JSXBase.HTMLAttributes<HTMLChangebotToastElement>;
        }
    }
}
