/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Theme } from "./utils/themes";
import { Update } from "./types";
export { Theme } from "./utils/themes";
export { Update } from "./types";
export namespace Components {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount": boolean;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        "scope"?: string;
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
        "toggle": () => Promise<void>;
    }
    interface ChangebotPanel {
        "close": () => Promise<void>;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode": 'modal' | 'drawer-left' | 'drawer-right';
        "open": () => Promise<void>;
        "scope"?: string;
        "setUpdates": (updates: Update[]) => Promise<void>;
        "theme"?: Theme;
    }
    interface ChangebotProvider {
        "baseUrl"?: string;
        "mockData"?: string;
        "preview"?: boolean;
        /**
          * @default 'default'
         */
        "scope": string;
        "slug"?: string;
        "userData"?: string;
        "userId"?: string;
    }
    interface ChangebotToast {
        "autoDismiss"?: number;
        "dark"?: Theme;
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
        "scope"?: string;
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
    }
}
declare global {
    interface HTMLChangebotBadgeElement extends Components.ChangebotBadge, HTMLStencilElement {
    }
    var HTMLChangebotBadgeElement: {
        prototype: HTMLChangebotBadgeElement;
        new (): HTMLChangebotBadgeElement;
    };
    interface HTMLChangebotBannerElement extends Components.ChangebotBanner, HTMLStencilElement {
    }
    var HTMLChangebotBannerElement: {
        prototype: HTMLChangebotBannerElement;
        new (): HTMLChangebotBannerElement;
    };
    interface HTMLChangebotPanelElement extends Components.ChangebotPanel, HTMLStencilElement {
    }
    var HTMLChangebotPanelElement: {
        prototype: HTMLChangebotPanelElement;
        new (): HTMLChangebotPanelElement;
    };
    interface HTMLChangebotProviderElement extends Components.ChangebotProvider, HTMLStencilElement {
    }
    var HTMLChangebotProviderElement: {
        prototype: HTMLChangebotProviderElement;
        new (): HTMLChangebotProviderElement;
    };
    interface HTMLChangebotToastElement extends Components.ChangebotToast, HTMLStencilElement {
    }
    var HTMLChangebotToastElement: {
        prototype: HTMLChangebotToastElement;
        new (): HTMLChangebotToastElement;
    };
    interface HTMLElementTagNameMap {
        "changebot-badge": HTMLChangebotBadgeElement;
        "changebot-banner": HTMLChangebotBannerElement;
        "changebot-panel": HTMLChangebotPanelElement;
        "changebot-provider": HTMLChangebotProviderElement;
        "changebot-toast": HTMLChangebotToastElement;
    }
}
declare namespace LocalJSX {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount"?: boolean;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotPanel {
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode"?: 'modal' | 'drawer-left' | 'drawer-right';
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotProvider {
        "baseUrl"?: string;
        "mockData"?: string;
        "preview"?: boolean;
        /**
          * @default 'default'
         */
        "scope"?: string;
        "slug"?: string;
        "userData"?: string;
        "userId"?: string;
    }
    interface ChangebotToast {
        "autoDismiss"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position"?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
        "scope"?: string;
        "theme"?: Theme;
    }
    interface IntrinsicElements {
        "changebot-badge": ChangebotBadge;
        "changebot-banner": ChangebotBanner;
        "changebot-panel": ChangebotPanel;
        "changebot-provider": ChangebotProvider;
        "changebot-toast": ChangebotToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "changebot-badge": LocalJSX.ChangebotBadge & JSXBase.HTMLAttributes<HTMLChangebotBadgeElement>;
            "changebot-banner": LocalJSX.ChangebotBanner & JSXBase.HTMLAttributes<HTMLChangebotBannerElement>;
            "changebot-panel": LocalJSX.ChangebotPanel & JSXBase.HTMLAttributes<HTMLChangebotPanelElement>;
            "changebot-provider": LocalJSX.ChangebotProvider & JSXBase.HTMLAttributes<HTMLChangebotProviderElement>;
            "changebot-toast": LocalJSX.ChangebotToast & JSXBase.HTMLAttributes<HTMLChangebotToastElement>;
        }
    }
}
