/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Theme } from "./utils/themes";
import { Update } from "./types";
export { Theme } from "./utils/themes";
export { Update } from "./types";
export namespace Components {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount": boolean;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        /**
          * Dismiss the banner
         */
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        "scope"?: string;
        /**
          * Show the banner with a specific update
         */
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
        /**
          * Toggle expanded state
         */
        "toggle": () => Promise<void>;
    }
    interface ChangebotPanel {
        /**
          * Close the panel
         */
        "close": () => Promise<void>;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode": 'modal' | 'drawer-left' | 'drawer-right';
        /**
          * Open the panel
         */
        "open": () => Promise<void>;
        "scope"?: string;
        /**
          * Set the updates to display
         */
        "setUpdates": (updates: Update[]) => Promise<void>;
        "theme"?: Theme;
    }
    interface ChangebotProvider {
        "pollInterval"?: number;
        /**
          * @default 'default'
         */
        "scope": string;
        "slug"?: string;
        "url"?: string;
    }
    interface ChangebotToast {
        "autoDismiss"?: number;
        "dark"?: Theme;
        /**
          * Dismiss the toast
         */
        "dismiss": () => Promise<void>;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
        "scope"?: string;
        /**
          * Show the toast with a specific update
         */
        "show": (update: Update) => Promise<void>;
        "theme"?: Theme;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface ChangebotPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChangebotPanelElement;
}
declare global {
    interface HTMLChangebotBadgeElement extends Components.ChangebotBadge, HTMLStencilElement {
    }
    var HTMLChangebotBadgeElement: {
        prototype: HTMLChangebotBadgeElement;
        new (): HTMLChangebotBadgeElement;
    };
    interface HTMLChangebotBannerElement extends Components.ChangebotBanner, HTMLStencilElement {
    }
    var HTMLChangebotBannerElement: {
        prototype: HTMLChangebotBannerElement;
        new (): HTMLChangebotBannerElement;
    };
    interface HTMLChangebotPanelElementEventMap {
        "changebot-last-viewed": { scope: string };
    }
    interface HTMLChangebotPanelElement extends Components.ChangebotPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChangebotPanelElementEventMap>(type: K, listener: (this: HTMLChangebotPanelElement, ev: ChangebotPanelCustomEvent<HTMLChangebotPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChangebotPanelElementEventMap>(type: K, listener: (this: HTMLChangebotPanelElement, ev: ChangebotPanelCustomEvent<HTMLChangebotPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChangebotPanelElement: {
        prototype: HTMLChangebotPanelElement;
        new (): HTMLChangebotPanelElement;
    };
    interface HTMLChangebotProviderElement extends Components.ChangebotProvider, HTMLStencilElement {
    }
    var HTMLChangebotProviderElement: {
        prototype: HTMLChangebotProviderElement;
        new (): HTMLChangebotProviderElement;
    };
    interface HTMLChangebotToastElement extends Components.ChangebotToast, HTMLStencilElement {
    }
    var HTMLChangebotToastElement: {
        prototype: HTMLChangebotToastElement;
        new (): HTMLChangebotToastElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "changebot-badge": HTMLChangebotBadgeElement;
        "changebot-banner": HTMLChangebotBannerElement;
        "changebot-panel": HTMLChangebotPanelElement;
        "changebot-provider": HTMLChangebotProviderElement;
        "changebot-toast": HTMLChangebotToastElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChangebotBadge {
        "count"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount"?: boolean;
        "theme"?: Theme;
    }
    interface ChangebotBanner {
        "dark"?: Theme;
        "light"?: Theme;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotPanel {
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'drawer-right'
         */
        "mode"?: 'modal' | 'drawer-left' | 'drawer-right';
        "onChangebot-last-viewed"?: (event: ChangebotPanelCustomEvent<{ scope: string }>) => void;
        "scope"?: string;
        "theme"?: Theme;
    }
    interface ChangebotProvider {
        "pollInterval"?: number;
        /**
          * @default 'default'
         */
        "scope"?: string;
        "slug"?: string;
        "url"?: string;
    }
    interface ChangebotToast {
        "autoDismiss"?: number;
        "dark"?: Theme;
        "light"?: Theme;
        /**
          * @default 'bottom-right'
         */
        "position"?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
        "scope"?: string;
        "theme"?: Theme;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "changebot-badge": ChangebotBadge;
        "changebot-banner": ChangebotBanner;
        "changebot-panel": ChangebotPanel;
        "changebot-provider": ChangebotProvider;
        "changebot-toast": ChangebotToast;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "changebot-badge": LocalJSX.ChangebotBadge & JSXBase.HTMLAttributes<HTMLChangebotBadgeElement>;
            "changebot-banner": LocalJSX.ChangebotBanner & JSXBase.HTMLAttributes<HTMLChangebotBannerElement>;
            "changebot-panel": LocalJSX.ChangebotPanel & JSXBase.HTMLAttributes<HTMLChangebotPanelElement>;
            "changebot-provider": LocalJSX.ChangebotProvider & JSXBase.HTMLAttributes<HTMLChangebotProviderElement>;
            "changebot-toast": LocalJSX.ChangebotToast & JSXBase.HTMLAttributes<HTMLChangebotToastElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
