'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChangebotBadge as ChangebotBadgeElement, defineCustomElement as defineChangebotBadge } from "@changebot/core/dist/components/changebot-badge.js";
import { ChangebotBanner as ChangebotBannerElement, defineCustomElement as defineChangebotBanner } from "@changebot/core/dist/components/changebot-banner.js";
import { ChangebotPanel as ChangebotPanelElement, defineCustomElement as defineChangebotPanel } from "@changebot/core/dist/components/changebot-panel.js";
import { ChangebotProvider as ChangebotProviderElement, defineCustomElement as defineChangebotProvider } from "@changebot/core/dist/components/changebot-provider.js";
import { ChangebotToast as ChangebotToastElement, defineCustomElement as defineChangebotToast } from "@changebot/core/dist/components/changebot-toast.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@changebot/core/dist/components/my-component.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type ChangebotBadgeEvents = NonNullable<unknown>;

export const ChangebotBadge: StencilReactComponent<ChangebotBadgeElement, ChangebotBadgeEvents> = /*@__PURE__*/ createComponent<ChangebotBadgeElement, ChangebotBadgeEvents>({
    tagName: 'changebot-badge',
    elementClass: ChangebotBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotBadgeEvents,
    defineCustomElement: defineChangebotBadge
});

export type ChangebotBannerEvents = NonNullable<unknown>;

export const ChangebotBanner: StencilReactComponent<ChangebotBannerElement, ChangebotBannerEvents> = /*@__PURE__*/ createComponent<ChangebotBannerElement, ChangebotBannerEvents>({
    tagName: 'changebot-banner',
    elementClass: ChangebotBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotBannerEvents,
    defineCustomElement: defineChangebotBanner
});

export type ChangebotPanelEvents = { onChangebotLastViewed: EventName<CustomEvent<{ scope: string }>> };

export const ChangebotPanel: StencilReactComponent<ChangebotPanelElement, ChangebotPanelEvents> = /*@__PURE__*/ createComponent<ChangebotPanelElement, ChangebotPanelEvents>({
    tagName: 'changebot-panel',
    elementClass: ChangebotPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChangebotLastViewed: 'changebot-last-viewed' } as ChangebotPanelEvents,
    defineCustomElement: defineChangebotPanel
});

export type ChangebotProviderEvents = NonNullable<unknown>;

export const ChangebotProvider: StencilReactComponent<ChangebotProviderElement, ChangebotProviderEvents> = /*@__PURE__*/ createComponent<ChangebotProviderElement, ChangebotProviderEvents>({
    tagName: 'changebot-provider',
    elementClass: ChangebotProviderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotProviderEvents,
    defineCustomElement: defineChangebotProvider
});

export type ChangebotToastEvents = NonNullable<unknown>;

export const ChangebotToast: StencilReactComponent<ChangebotToastElement, ChangebotToastEvents> = /*@__PURE__*/ createComponent<ChangebotToastElement, ChangebotToastEvents>({
    tagName: 'changebot-toast',
    elementClass: ChangebotToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotToastEvents,
    defineCustomElement: defineChangebotToast
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
