'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@changebot/core/dist/components";
import { ChangebotBadge as ChangebotBadgeElement, defineCustomElement as defineChangebotBadge } from "@changebot/core/dist/components/changebot-badge.js";
import { ChangebotBanner as ChangebotBannerElement, defineCustomElement as defineChangebotBanner } from "@changebot/core/dist/components/changebot-banner.js";
import { ChangebotPanel as ChangebotPanelElement, defineCustomElement as defineChangebotPanel } from "@changebot/core/dist/components/changebot-panel.js";
import { ChangebotProvider as ChangebotProviderElement, defineCustomElement as defineChangebotProvider } from "@changebot/core/dist/components/changebot-provider.js";
import { ChangebotToast as ChangebotToastElement, defineCustomElement as defineChangebotToast } from "@changebot/core/dist/components/changebot-toast.js";

export type ChangebotBadgeEvents = NonNullable<unknown>;

export const ChangebotBadge: StencilReactComponent<ChangebotBadgeElement, ChangebotBadgeEvents, Components.ChangebotBadge> = /*@__PURE__*/ createComponent<ChangebotBadgeElement, ChangebotBadgeEvents, Components.ChangebotBadge>({
    tagName: 'changebot-badge',
    elementClass: ChangebotBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotBadgeEvents,
    defineCustomElement: defineChangebotBadge
});

export type ChangebotBannerEvents = NonNullable<unknown>;

export const ChangebotBanner: StencilReactComponent<ChangebotBannerElement, ChangebotBannerEvents, Components.ChangebotBanner> = /*@__PURE__*/ createComponent<ChangebotBannerElement, ChangebotBannerEvents, Components.ChangebotBanner>({
    tagName: 'changebot-banner',
    elementClass: ChangebotBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotBannerEvents,
    defineCustomElement: defineChangebotBanner
});

export type ChangebotPanelEvents = NonNullable<unknown>;

export const ChangebotPanel: StencilReactComponent<ChangebotPanelElement, ChangebotPanelEvents, Components.ChangebotPanel> = /*@__PURE__*/ createComponent<ChangebotPanelElement, ChangebotPanelEvents, Components.ChangebotPanel>({
    tagName: 'changebot-panel',
    elementClass: ChangebotPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotPanelEvents,
    defineCustomElement: defineChangebotPanel
});

export type ChangebotProviderEvents = NonNullable<unknown>;

export const ChangebotProvider: StencilReactComponent<ChangebotProviderElement, ChangebotProviderEvents, Components.ChangebotProvider> = /*@__PURE__*/ createComponent<ChangebotProviderElement, ChangebotProviderEvents, Components.ChangebotProvider>({
    tagName: 'changebot-provider',
    elementClass: ChangebotProviderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotProviderEvents,
    defineCustomElement: defineChangebotProvider
});

export type ChangebotToastEvents = NonNullable<unknown>;

export const ChangebotToast: StencilReactComponent<ChangebotToastElement, ChangebotToastEvents, Components.ChangebotToast> = /*@__PURE__*/ createComponent<ChangebotToastElement, ChangebotToastEvents, Components.ChangebotToast>({
    tagName: 'changebot-toast',
    elementClass: ChangebotToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ChangebotToastEvents,
    defineCustomElement: defineChangebotToast
});
