/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Update } from "./types";
export { Update } from "./types";
export namespace Components {
    interface ChangebotBadge {
        "count"?: number;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount": boolean;
        "theme"?: 'light' | 'dark';
    }
    interface ChangebotDrawer {
        /**
          * Close the drawer/modal
         */
        "close": () => Promise<void>;
        /**
          * @default 'drawer-right'
         */
        "displayMode": 'drawer-left' | 'drawer-right' | 'modal';
        /**
          * Open the drawer/modal
         */
        "open": () => Promise<void>;
        "scope"?: string;
        /**
          * Set the updates to display
         */
        "setUpdates": (updates: Update[]) => Promise<void>;
        "theme"?: 'light' | 'dark';
    }
    interface ChangebotProvider {
        "pollInterval"?: number;
        /**
          * @default 'default'
         */
        "scope": string;
        "slug"?: string;
        "url"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLChangebotBadgeElement extends Components.ChangebotBadge, HTMLStencilElement {
    }
    var HTMLChangebotBadgeElement: {
        prototype: HTMLChangebotBadgeElement;
        new (): HTMLChangebotBadgeElement;
    };
    interface HTMLChangebotDrawerElement extends Components.ChangebotDrawer, HTMLStencilElement {
    }
    var HTMLChangebotDrawerElement: {
        prototype: HTMLChangebotDrawerElement;
        new (): HTMLChangebotDrawerElement;
    };
    interface HTMLChangebotProviderElement extends Components.ChangebotProvider, HTMLStencilElement {
    }
    var HTMLChangebotProviderElement: {
        prototype: HTMLChangebotProviderElement;
        new (): HTMLChangebotProviderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "changebot-badge": HTMLChangebotBadgeElement;
        "changebot-drawer": HTMLChangebotDrawerElement;
        "changebot-provider": HTMLChangebotProviderElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChangebotBadge {
        "count"?: number;
        "scope"?: string;
        /**
          * @default true
         */
        "showCount"?: boolean;
        "theme"?: 'light' | 'dark';
    }
    interface ChangebotDrawer {
        /**
          * @default 'drawer-right'
         */
        "displayMode"?: 'drawer-left' | 'drawer-right' | 'modal';
        "scope"?: string;
        "theme"?: 'light' | 'dark';
    }
    interface ChangebotProvider {
        "pollInterval"?: number;
        /**
          * @default 'default'
         */
        "scope"?: string;
        "slug"?: string;
        "url"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "changebot-badge": ChangebotBadge;
        "changebot-drawer": ChangebotDrawer;
        "changebot-provider": ChangebotProvider;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "changebot-badge": LocalJSX.ChangebotBadge & JSXBase.HTMLAttributes<HTMLChangebotBadgeElement>;
            "changebot-drawer": LocalJSX.ChangebotDrawer & JSXBase.HTMLAttributes<HTMLChangebotDrawerElement>;
            "changebot-provider": LocalJSX.ChangebotProvider & JSXBase.HTMLAttributes<HTMLChangebotProviderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
